/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    media: Media;
    'photo-drafts': PhotoDraft;
    policies: Policy;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'photo-drafts': PhotoDraftsSelect<false> | PhotoDraftsSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Everything the shop sells. Click a product to change its photos, price or stock.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * What a customer sees, e.g. "Engraved Brass Kalash — Size 2".
   */
  title: string;
  /**
   * Drag photos in, or send them from a phone in the Photo studio. The first is the main picture — drag to reorder. Needed before this can go live, not before it can be saved.
   */
  photos?: (number | Media)[] | null;
  /**
   * What the customer pays. Needed before it goes live.
   */
  price?: number | null;
  /**
   * Leave blank if there is no discount. Must not be below the selling price.
   */
  mrp?: number | null;
  /**
   * Set to 0 and the product shows as sold out. It stays on the site.
   */
  stock: number;
  /**
   * Which part of the shop this belongs to.
   */
  category?: (number | null) | Category;
  /**
   * The kind of thing, within the section above.
   */
  subCategory?: string | null;
  /**
   * A few honest sentences. What it is, what it is made of, who it suits.
   */
  description?: string | null;
  /**
   * Lets customers filter by the occasion they are shopping for.
   */
  occasions?: ('birthday' | 'wedding' | 'festival' | 'everyday')[] | null;
  /**
   * Read it off the tag. Do not guess — a wrong declaration is a legal problem.
   */
  countryOfOrigin?: string | null;
  /**
   * Name and address as printed on the label.
   */
  manufacturer?: string | null;
  /**
   * What the thing is, plainly: "Brass idol", "Handbag".
   */
  genericName?: string | null;
  /**
   * e.g. "1 piece", "Set of 4".
   */
  netQuantity?: string | null;
  dimensions?: string | null;
  weight?: string | null;
  finish?: string | null;
  /**
   * e.g. "March 2026". Required on imported goods.
   */
  monthYearOfImport?: string | null;
  /**
   * New products start as a draft. Photograph and price them now, write the description later, then set this to Live.
   */
  status: 'draft' | 'live' | 'hidden';
  /**
   * Filled in automatically the first time this is set to Live.
   */
  publishedAt?: string | null;
  /**
   * The web address of this page. Filled in automatically. Changing it breaks links already shared.
   */
  slug?: string | null;
  /**
   * Puts this product in the scrolling row on the home page. Four to eight products keeps that row moving nicely.
   */
  featured?: boolean | null;
  /**
   * A few words over the photo, e.g. "Under ₹500". Falls back to the product name.
   */
  shortCaption?: string | null;
  /**
   * The small badge in the corner, e.g. "New drop", "Bestseller". Optional.
   */
  shortSticker?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every photo used on the site. You can also add photos straight from a product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * One short line for anyone using a screen reader, e.g. "Brass Krishna idol with a flute". Falls back to the product name.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The sections of the shop. Every product belongs to one. Lower order numbers come first in the menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Shown as the section heading, e.g. "Home & Décor".
   */
  name: string;
  /**
   * The one word that fits in the top menu, e.g. "Decor".
   */
  shortName: string;
  /**
   * The web address of this page. Filled in automatically. Changing it breaks links already shared.
   */
  slug?: string | null;
  /**
   * One or two lines under the heading. Optional.
   */
  blurb?: string | null;
  /**
   * The kinds of thing in this section — wall clocks, photo frames, idols. These become the Category dropdown on a product, and are listed on the section tile.
   */
  subCategories?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers come first in the menu.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos sent from a phone, waiting to be checked and attached to a product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-drafts".
 */
export interface PhotoDraft {
  id: number;
  /**
   * Typed on the phone while the product is in hand. The tablet pre-fills the product name from this, so nobody has to work out later what the photo was of.
   */
  suggestedName?: string | null;
  /**
   * Optional. If the person shooting knows, it saves picking it again on the tablet.
   */
  suggestedProduct?: (number | null) | Product;
  /**
   * Anything the tablet should know — "back view", "damaged corner".
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Terms, privacy, returns and the compliance disclosures. Read these before the shop takes its first order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  title: string;
  /**
   * The web address of this page. Filled in automatically. Changing it breaks links already shared.
   */
  slug?: string | null;
  /**
   * Shown under the heading and in search results.
   */
  summary?: string | null;
  /**
   * Each becomes a heading and its paragraphs.
   */
  sections?:
    | {
        heading: string;
        /**
         * Leave a blank line between paragraphs.
         */
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * On until someone who knows the business — ideally a lawyer — has read this page. While it is on, the page carries a visible notice.
   */
  needsReview?: boolean | null;
  /**
   * Lower numbers come first in the footer.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the corner of the admin. Yours to set.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'photo-drafts';
        value: number | PhotoDraft;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  photos?: T;
  price?: T;
  mrp?: T;
  stock?: T;
  category?: T;
  subCategory?: T;
  description?: T;
  occasions?: T;
  countryOfOrigin?: T;
  manufacturer?: T;
  genericName?: T;
  netQuantity?: T;
  dimensions?: T;
  weight?: T;
  finish?: T;
  monthYearOfImport?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  featured?: T;
  shortCaption?: T;
  shortSticker?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  blurb?: T;
  subCategories?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-drafts_select".
 */
export interface PhotoDraftsSelect<T extends boolean = true> {
  suggestedName?: T;
  suggestedProduct?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  needsReview?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The phone number, address, hours and the words on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Country code first, digits only, no plus and no spaces. India is 91, so: 919666662472.
   */
  whatsappNumber: string;
  /**
   * How it appears on the page. Spaces are fine here.
   */
  displayPhone?: string | null;
  email?: string | null;
  address?: string | null;
  hours?: string | null;
  /**
   * Optional. Paste the share link from Google Maps.
   */
  mapsUrl?: string | null;
  /**
   * Shown in the strip under the header. Leave blank to hide it.
   */
  gstin?: string | null;
  /**
   * Required of every Indian e-commerce seller by the Consumer Protection (E-Commerce) Rules, 2020. Appears in the footer.
   */
  grievance?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    /**
     * e.g. acknowledged within 48 hours, resolved within a month.
     */
    note?: string | null;
  };
  youtubeHandle?: string | null;
  instagramUrl?: string | null;
  /**
   * e.g. "Made by", "Designed by".
   */
  agencyCredit?: string | null;
  agencyName?: string | null;
  /**
   * Shown under the first, joined by an "&". Clear both this and the name below to show one credit line only.
   */
  maintainerCredit?: string | null;
  maintainerName?: string | null;
  /**
   * Leave blank and the name shows as plain text.
   */
  maintainerUrl?: string | null;
  /**
   * Off until the image file is in place at /public/made-in-india.png. The Government of India’s own "Make in India" lion is a protected mark and needs DPIIT permission — a plain "Made in India" badge does not.
   */
  madeInIndia?: boolean | null;
  /**
   * Leave blank and the name shows as plain text.
   */
  agencyUrl?: string | null;
  /**
   * Leave blank to hide that strip entirely.
   */
  announcement?: string | null;
  heroEyebrow?: string | null;
  heroHeadline?: string | null;
  heroBody?: string | null;
  subscriberCount?: string | null;
  /**
   * Pixels a second. 11 is a slow, readable drift. 18 was the old Midnight site. Anything past 25 is too fast to read a price off. Change it here and the site picks it up within a minute — no code needed.
   */
  shortsSpeed?: number | null;
  aboutText?: string | null;
  deliveryFee?: number | null;
  /**
   * Set to 0 to make delivery free on everything.
   */
  freeDeliveryOver?: number | null;
  deliveryNote?: string | null;
  /**
   * Shown on the home page and the contact page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  whatsappNumber?: T;
  displayPhone?: T;
  email?: T;
  address?: T;
  hours?: T;
  mapsUrl?: T;
  gstin?: T;
  grievance?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        note?: T;
      };
  youtubeHandle?: T;
  instagramUrl?: T;
  agencyCredit?: T;
  agencyName?: T;
  maintainerCredit?: T;
  maintainerName?: T;
  maintainerUrl?: T;
  madeInIndia?: T;
  agencyUrl?: T;
  announcement?: T;
  heroEyebrow?: T;
  heroHeadline?: T;
  heroBody?: T;
  subscriberCount?: T;
  shortsSpeed?: T;
  aboutText?: T;
  deliveryFee?: T;
  freeDeliveryOver?: T;
  deliveryNote?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}